spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/parking
    username: root
    password: 123456
  thymeleaf:
    cache: false
    cache-period: 0
  templates:
    cache: false